[package]
name = "restaurant_use"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
restaurant = { git = "https://github.com/Gabriel-CR/reuso_software/", branch = "main" }
